<?php
// $Id$

/**
 * @file
 *
 * Remove taxonomies from display
 */

/**
 * Implementation of hook_help().
 */
function hide_taxonomy_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('Hide taxonomies from display.');
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function hide_taxonomy_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
      $taxonomies_to_hide = variable_get('hide_taxonomy_taxonomies', array());

      foreach (variable_get('hide_taxonomy_taxonomies', array()) as $vid => $selected) {
        if ($selected) {
          foreach ($node->taxonomy as $term) {
            if ($term->vid == $vid) {
              unset($node->taxonomy[$term->tid]);
            }
          }
        }
      }
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function hide_taxonomy_menu() {
  $items = array();

  $items['admin/settings/hide_taxonomy'] = array(
    'title' => 'Hide taxonomy',
    'description' => 'Select what taxonomies are to be hidden.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hide_taxonomy_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function hide_taxonomy_admin_settings() {
  $vocabs = taxonomy_get_vocabularies();

  $voptions = array();

  foreach ($vocabs as $vocab) {
    $voptions[$vocab->vid] = $vocab->name;
  }

  $form['hide_taxonomy_taxonomies'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Which taxonomies?'),
      '#options' => $voptions,
      '#default_value' => variable_get('hide_taxonomy_taxonomies', array()),
  );

  return system_settings_form($form);
}


